import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from "react";

export type AppCurrency = "EUR" | "UAH" | "USD";
export type AppLanguage = "uk" | "ru" | "en";

interface PreferencesContextType {
  currency: AppCurrency;
  language: AppLanguage;
  setCurrency: (currency: AppCurrency) => void;
  setLanguage: (language: AppLanguage) => void;
  locale: string;
}

type TranslationTree = { [key: string]: string | TranslationTree };
type TranslationParams = Record<string, string | number>;

const STORAGE_KEY = "warehouseme-preferences";

const getLocaleFromLanguage = (language: AppLanguage): string => {
  switch (language) {
    case "en":
      return "en-US";
    case "ru":
      return "ru-RU";
    case "uk":
    default:
      return "uk-UA";
  }
};

const translations: Record<AppLanguage, TranslationTree> = {
  uk: {
    nav: {
      home: "Головна",
      items: "Речі",
      allItems: "Усі речі",
      locations: "Локації",
      categories: "Категорії",
      expiry: "Терміни",
      statistics: "Статистика",
      settings: "Налаштування",
      more: "Ще",
      logout: "Вийти",
      collapse: "Згорнути",
    },
    common: {
      save: "Зберегти",
      cancel: "Скасувати",
      delete: "Видалити",
      edit: "Редагувати",
      add: "Додати",
      back: "Назад",
      loading: "Завантаження...",
      error: "Помилка",
      search: "Пошук",
      all: "Усі",
      copied: "Скопійовано",
      rootCategory: "Коренева категорія",
      rootLocation: "Коренева локація",
      user: "Користувач",
      month: "За місяць",
      year: "За рік",
      noData: "Немає даних",
      days: "днів",
      until: "до",
    },
    auth: {
      subtitle: "Домашній інвентар речей",
      loginTitle: "Вхід в акаунт",
      registerTitle: "Реєстрація",
      resetTitle: "Відновлення пароля",
      loginDescription: "Увійдіть, щоб керувати своїм інвентарем",
      registerDescription: "Створіть акаунт для початку роботи",
      resetDescription: "Введіть email для отримання посилання на відновлення",
      name: "Ім'я",
      yourName: "Ваше ім'я",
      email: "Email",
      password: "Пароль",
      login: "Увійти",
      register: "Зареєструватися",
      sendLink: "Надіслати посилання",
      forgotPassword: "Забули пароль?",
      noAccount: "Немає акаунта?",
      signUp: "Зареєструйтеся",
      haveAccount: "Вже є акаунт?",
      signIn: "Увійдіть",
      backToLogin: "Повернутися до входу",
      registerSuccess: "Реєстрація успішна",
      welcome: "Ласкаво просимо до WarehouseMe!",
      emailSent: "Лист надіслано",
      checkEmail: "Перевірте пошту для відновлення пароля.",
    },
    dashboard: {
      totalItems: "Усього речей",
      totalValue: "Загальна вартість",
      expiry: "Термін придатності ⚠️",
      thisMonth: "Цього місяця",
      searchPlaceholder: "Пошук по всіх речах...",
      expiringTitle: "Термін придатності закінчується",
      recentTitle: "Нещодавно додані",
      viewAll: "Усі →",
      noItems: "Поки немає речей",
      addFirstItem: "Додати першу річ",
      expired: "Прострочено",
      daysShort: "дн.",
    },
    settings: {
      title: "Налаштування",
      profile: "Профіль",
      preferences: "Параметри",
      defaultCurrency: "Валюта за замовчуванням",
      language: "Мова",
      data: "Дані",
      exportCsv: "Експорт у CSV",
      exportPdf: "Експорт у PDF",
      importCsv: "Імпорт з CSV",
      importing: "Імпортування...",
      importSuccess: "Імпортовано речей: {count}",
      importError: "Помилка імпорту",
      account: "Акаунт",
      logout: "Вийти з акаунта",
    },
    languages: {
      uk: "Українська",
      ru: "Русский",
      en: "English",
    },
    currencies: {
      EUR: "Євро (€)",
      UAH: "Гривня (₴)",
      USD: "Долар ($)",
    },
    items: {
      title: "Усі речі",
      searchPlaceholder: "Пошук...",
      category: "Категорія",
      allCategories: "Усі категорії",
      allLocations: "Усі локації",
      sort: "Сортування",
      sortDate: "За датою",
      sortName: "За назвою",
      sortPrice: "За ціною",
      sortExpiry: "За терміном придатності",
      noItems: "Немає речей",
      addItem: "Додати річ",
      boughtOn: "Куплено:",
      expired: "Прострочено",
      daysShort: "дн.",
    },
    categories: {
      title: "Категорії",
      namePlaceholder: "Назва категорії",
      editTitle: "Редагувати категорію",
      name: "Назва",
      addFirst: "Додайте першу категорію",
      loadStandard: "Завантажити стандартні категорії",
      deleteTitle: "Видалити категорію?",
      deleteDescription: "Підкатегорії теж буде видалено. Речі залишаться без категорії.",
      addSubcategory: "Додати підкатегорію",
      seeded: "Категорії додано!",
    },
    locations: {
      title: "Локації",
      namePlaceholder: "Назва локації",
      editTitle: "Редагувати локацію",
      addFirst: "Додайте першу локацію",
      deleteTitle: "Видалити локацію?",
      deleteDescription: "Усі підлокації теж буде видалено.",
    },
    itemForm: {
      addTitle: "Додати річ",
      editTitle: "Редагувати річ",
      stepBasic: "Основне",
      stepLocation: "Місце",
      stepPurchase: "Покупка",
      stepNotes: "Нотатки",
      name: "Назва *",
      namePlaceholder: "Наприклад: MacBook Pro",
      description: "Опис",
      descriptionPlaceholder: "Опис речі",
      barcode: "Штрихкод (пошук товару)",
      barcodePlaceholder: "Введіть штрихкод",
      barcodeHint: "Введіть штрихкод і натисніть пошук для автозаповнення",
      photo: "Фото товару",
      uploadPhoto: "Натисніть для завантаження фото",
      maxFile: "Макс. 5 МБ",
      useIcon: "Використовувати іконку замість фото",
      itemIcon: "Іконка товару",
      category: "Категорія",
      selectCategory: "Виберіть категорію",
      newCategory: "Нова категорія",
      location: "Локація",
      selectLocation: "Виберіть локацію",
      newLocation: "Нова локація",
      purchaseDate: "Дата покупки",
      price: "Ціна",
      currency: "Валюта",
      hasExpiry: "Є термін придатності",
      expiryDate: "Дата закінчення терміну придатності",
      serial: "Серійний номер",
      notes: "Нотатки",
      notesPlaceholder: "Додаткова інформація...",
      next: "Далі",
      back: "Назад",
      cancel: "Скасувати",
      save: "Зберегти",
      uploading: "Завантаження...",
      fileTooLarge: "Файл занадто великий",
      fileTooLargeDescription: "Максимум 5 МБ",
      uploadError: "Помилка завантаження фото",
      found: "Товар знайдено!",
      filled: "Дані заповнено автоматично",
      notFound: "Товар не знайдено",
      fillManual: "Спробуйте ввести дані вручну",
    },
    itemDetail: {
      notFound: "Річ не знайдено",
      backToList: "Повернутися до списку",
      edit: "Редагувати",
      deleteTitle: "Видалити річ?",
      deleteDescription: "Цю дію не можна скасувати.",
      location: "Місцезнаходження",
      purchaseDate: "Дата покупки",
      price: "Ціна",
      expiry: "Термін придатності",
      expired: "Прострочено",
      expiring: "Закінчується",
      active: "Придатний",
      daysLeft: "днів залишилося",
      serial: "Серійний номер",
      barcode: "Штрихкод",
      notes: "Нотатки",
    },
    expiry: {
      title: "Терміни придатності",
      criticalOne: "річ стане простроченою менш ніж через 7 днів!",
      criticalMany: "речей стануть простроченими менш ніж через 7 днів!",
      expiring: "Закінчується",
      active: "Придатні",
      expired: "Прострочено",
      noExpiring: "Немає речей із терміном, що закінчується",
      noActive: "Немає речей з активним терміном придатності",
      noExpired: "Немає прострочених речей",
      expiredShort: "прострочено",
      days: "днів",
    },
    statistics: {
      title: "Статистика",
      totalItems: "Усього речей",
      totalValue: "Вартість",
      average: "Середня",
      byCategories: "За категоріями",
      byLocations: "За локаціями",
      byMonths: "За місяцями",
      expiry: "Терміни придатності",
      active: "Придатні",
      expiringMonth: "Закінчується цього місяця",
      expired: "Прострочено",
      topFive: "Топ-5 найдорожчих",
    },
    finance: {
      title: "Фінанси",
      totalSpent: "Загальні витрати",
      purchases: "покупок",
      byDay: "Витрати по днях",
      byMonths: "Витрати по місяцях ({year})",
      byCategories: "Витрати за категоріями ({period})",
      recent: "Останні покупки",
    },
    notFound: {
      title: "Сторінку не знайдено",
      backHome: "Повернутися на головну",
    },
    toasts: {
      itemAdded: "Річ додано",
      itemUpdated: "Річ оновлено",
      itemDeleted: "Річ видалено",
      categoryCreated: "Категорію створено",
      categoryUpdated: "Категорію оновлено",
      categoryDeleted: "Категорію видалено",
      locationCreated: "Локацію створено",
      locationUpdated: "Локацію оновлено",
      locationDeleted: "Локацію видалено",
      lookupError: "Помилка пошуку",
      savedOffline: "Збережено офлайн",
    },
    offline: {
      noConnection: "Немає з'єднання",
      pending: "в черзі",
      sync: "Синхронізувати",
    },
  },
  ru: {
    nav: {
      home: "Главная",
      items: "Вещи",
      allItems: "Все вещи",
      locations: "Локации",
      categories: "Категории",
      expiry: "Сроки",
      statistics: "Статистика",
      settings: "Настройки",
      more: "Ещё",
      logout: "Выйти",
      collapse: "Свернуть",
    },
    common: {
      save: "Сохранить",
      cancel: "Отмена",
      delete: "Удалить",
      edit: "Редактировать",
      add: "Добавить",
      back: "Назад",
      loading: "Загрузка...",
      error: "Ошибка",
      search: "Поиск",
      all: "Все",
      copied: "Скопировано",
      rootCategory: "Корневая категория",
      rootLocation: "Корневая локация",
      user: "Пользователь",
      month: "За месяц",
      year: "За год",
      noData: "Нет данных",
      days: "дней",
      until: "до",
    },
    auth: {
      subtitle: "Домашний инвентарь вещей",
      loginTitle: "Вход в аккаунт",
      registerTitle: "Регистрация",
      resetTitle: "Восстановление пароля",
      loginDescription: "Войдите, чтобы управлять вашим инвентарём",
      registerDescription: "Создайте аккаунт для начала работы",
      resetDescription: "Введите email для получения ссылки на восстановление",
      name: "Имя",
      yourName: "Ваше имя",
      email: "Email",
      password: "Пароль",
      login: "Войти",
      register: "Зарегистрироваться",
      sendLink: "Отправить ссылку",
      forgotPassword: "Забыли пароль?",
      noAccount: "Нет аккаунта?",
      signUp: "Зарегистрируйтесь",
      haveAccount: "Уже есть аккаунт?",
      signIn: "Войдите",
      backToLogin: "Вернуться ко входу",
      registerSuccess: "Регистрация успешна",
      welcome: "Добро пожаловать в WarehouseMe!",
      emailSent: "Письмо отправлено",
      checkEmail: "Проверьте почту для восстановления пароля.",
    },
    dashboard: {
      totalItems: "Всего вещей",
      totalValue: "Общая стоимость",
      expiry: "Срок годности ⚠️",
      thisMonth: "В этом месяце",
      searchPlaceholder: "Поиск по всем вещам...",
      expiringTitle: "Срок годности заканчивается",
      recentTitle: "Недавно добавленные",
      viewAll: "Все →",
      noItems: "Пока нет вещей",
      addFirstItem: "Добавить первую вещь",
      expired: "Просрочено",
      daysShort: "дн.",
    },
    settings: {
      title: "Настройки",
      profile: "Профиль",
      preferences: "Предпочтения",
      defaultCurrency: "Валюта по умолчанию",
      language: "Язык",
      data: "Данные",
      exportCsv: "Экспорт в CSV",
      exportPdf: "Экспорт в PDF",
      importCsv: "Импорт из CSV",
      importing: "Импортирование...",
      importSuccess: "Импортировано вещей: {count}",
      importError: "Ошибка импорта",
      account: "Аккаунт",
      logout: "Выйти из аккаунта",
    },
    languages: {
      uk: "Українська",
      ru: "Русский",
      en: "English",
    },
    currencies: {
      EUR: "Евро (€)",
      UAH: "Гривна (₴)",
      USD: "Доллар ($)",
    },
    items: {
      title: "Все вещи",
      searchPlaceholder: "Поиск...",
      category: "Категория",
      allCategories: "Все категории",
      allLocations: "Все локации",
      sort: "Сортировка",
      sortDate: "По дате",
      sortName: "По имени",
      sortPrice: "По цене",
      sortExpiry: "По сроку годности",
      noItems: "Нет вещей",
      addItem: "Добавить вещь",
      boughtOn: "Куплено:",
      expired: "Просрочено",
      daysShort: "дн.",
    },
    categories: {
      title: "Категории",
      namePlaceholder: "Название категории",
      editTitle: "Редактировать категорию",
      name: "Название",
      addFirst: "Добавьте первую категорию",
      loadStandard: "Загрузить стандартные категории",
      deleteTitle: "Удалить категорию?",
      deleteDescription: "Подкатегории тоже будут удалены. Вещи останутся без категории.",
      addSubcategory: "Добавить подкатегорию",
      seeded: "Категории добавлены!",
    },
    locations: {
      title: "Локации",
      namePlaceholder: "Название локации",
      editTitle: "Редактировать локацию",
      addFirst: "Добавьте первую локацию",
      deleteTitle: "Удалить локацию?",
      deleteDescription: "Все подлокации тоже будут удалены.",
    },
    itemForm: {
      addTitle: "Добавить вещь",
      editTitle: "Редактировать вещь",
      stepBasic: "Основное",
      stepLocation: "Место",
      stepPurchase: "Покупка",
      stepNotes: "Заметки",
      name: "Название *",
      namePlaceholder: "Например: MacBook Pro",
      description: "Описание",
      descriptionPlaceholder: "Описание вещи",
      barcode: "Штрихкод (поиск товара)",
      barcodePlaceholder: "Введите штрихкод",
      barcodeHint: "Введите штрихкод и нажмите поиск для автозаполнения",
      photo: "Фото товара",
      uploadPhoto: "Нажмите для загрузки фото",
      maxFile: "Макс. 5 МБ",
      useIcon: "Использовать иконку вместо фото",
      itemIcon: "Иконка товара",
      category: "Категория",
      selectCategory: "Выберите категорию",
      newCategory: "Новая категория",
      location: "Локация",
      selectLocation: "Выберите локацию",
      newLocation: "Новая локация",
      purchaseDate: "Дата покупки",
      price: "Цена",
      currency: "Валюта",
      hasExpiry: "Есть срок годности",
      expiryDate: "Дата окончания срока годности",
      serial: "Серийный номер",
      notes: "Заметки",
      notesPlaceholder: "Дополнительная информация...",
      next: "Далее",
      back: "Назад",
      cancel: "Отмена",
      save: "Сохранить",
      uploading: "Загрузка...",
      fileTooLarge: "Файл слишком большой",
      fileTooLargeDescription: "Максимум 5 МБ",
      uploadError: "Ошибка загрузки фото",
      found: "Товар найден!",
      filled: "Данные заполнены автоматически",
      notFound: "Товар не найден",
      fillManual: "Попробуйте ввести данные вручную",
    },
    itemDetail: {
      notFound: "Вещь не найдена",
      backToList: "Вернуться к списку",
      edit: "Редактировать",
      deleteTitle: "Удалить вещь?",
      deleteDescription: "Это действие нельзя отменить.",
      location: "Местонахождение",
      purchaseDate: "Дата покупки",
      price: "Цена",
      expiry: "Срок годности",
      expired: "Просрочено",
      expiring: "Заканчивается",
      active: "Годен",
      daysLeft: "дней осталось",
      serial: "Серийный номер",
      barcode: "Штрихкод",
      notes: "Заметки",
    },
    expiry: {
      title: "Сроки годности",
      criticalOne: "вещь просрочивается менее чем через 7 дней!",
      criticalMany: "вещей просрочиваются менее чем через 7 дней!",
      expiring: "Заканчивается",
      active: "Годные",
      expired: "Просрочено",
      noExpiring: "Нет вещей с заканчивающимся сроком",
      noActive: "Нет вещей с активным сроком годности",
      noExpired: "Нет просроченных вещей",
      expiredShort: "просрочено",
      days: "дней",
    },
    statistics: {
      title: "Статистика",
      totalItems: "Всего вещей",
      totalValue: "Стоимость",
      average: "Средняя",
      byCategories: "По категориям",
      byLocations: "По локациям",
      byMonths: "По месяцам",
      expiry: "Сроки годности",
      active: "Годные",
      expiringMonth: "Заканчивается в этом месяце",
      expired: "Просрочено",
      topFive: "Топ-5 самых дорогих",
    },
    finance: {
      title: "Финансы",
      totalSpent: "Общие расходы",
      purchases: "покупок",
      byDay: "Расходы по дням",
      byMonths: "Расходы по месяцам ({year})",
      byCategories: "Расходы по категориям ({period})",
      recent: "Последние покупки",
    },
    notFound: {
      title: "Страница не найдена",
      backHome: "Вернуться на главную",
    },
    toasts: {
      itemAdded: "Вещь добавлена",
      itemUpdated: "Вещь обновлена",
      itemDeleted: "Вещь удалена",
      categoryCreated: "Категория создана",
      categoryUpdated: "Категория обновлена",
      categoryDeleted: "Категория удалена",
      locationCreated: "Локация создана",
      locationUpdated: "Локация обновлена",
      locationDeleted: "Локация удалена",
      lookupError: "Ошибка поиска",
      savedOffline: "Сохранено офлайн",
    },
    offline: {
      noConnection: "Нет соединения",
      pending: "в очереди",
      sync: "Синхронизировать",
    },
  },
  en: {
    nav: {
      home: "Home",
      items: "Items",
      allItems: "All items",
      locations: "Locations",
      categories: "Categories",
      expiry: "Expiry",
      statistics: "Statistics",
      settings: "Settings",
      more: "More",
      logout: "Sign out",
      collapse: "Collapse",
    },
    common: {
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      add: "Add",
      back: "Back",
      loading: "Loading...",
      error: "Error",
      search: "Search",
      all: "All",
      copied: "Copied",
      rootCategory: "Root category",
      rootLocation: "Root location",
      user: "User",
      month: "By month",
      year: "By year",
      noData: "No data",
      days: "days",
      until: "until",
    },
    auth: {
      subtitle: "Home inventory manager",
      loginTitle: "Sign in",
      registerTitle: "Create account",
      resetTitle: "Reset password",
      loginDescription: "Sign in to manage your inventory",
      registerDescription: "Create an account to get started",
      resetDescription: "Enter your email to receive a reset link",
      name: "Name",
      yourName: "Your name",
      email: "Email",
      password: "Password",
      login: "Sign in",
      register: "Sign up",
      sendLink: "Send link",
      forgotPassword: "Forgot password?",
      noAccount: "No account?",
      signUp: "Sign up",
      haveAccount: "Already have an account?",
      signIn: "Sign in",
      backToLogin: "Back to sign in",
      registerSuccess: "Registration successful",
      welcome: "Welcome to WarehouseMe!",
      emailSent: "Email sent",
      checkEmail: "Check your inbox to reset your password.",
    },
    dashboard: {
      totalItems: "Total items",
      totalValue: "Total value",
      expiry: "Expiry ⚠️",
      thisMonth: "This month",
      searchPlaceholder: "Search all items...",
      expiringTitle: "Expiring soon",
      recentTitle: "Recently added",
      viewAll: "View all →",
      noItems: "No items yet",
      addFirstItem: "Add first item",
      expired: "Expired",
      daysShort: "d",
    },
    settings: {
      title: "Settings",
      profile: "Profile",
      preferences: "Preferences",
      defaultCurrency: "Default currency",
      language: "Language",
      data: "Data",
      exportCsv: "Export to CSV",
      exportPdf: "Export to PDF",
      importCsv: "Import from CSV",
      importing: "Importing...",
      importSuccess: "Imported items: {count}",
      importError: "Import error",
      account: "Account",
      logout: "Sign out",
    },
    languages: {
      uk: "Ukrainian",
      ru: "Russian",
      en: "English",
    },
    currencies: {
      EUR: "Euro (€)",
      UAH: "Hryvnia (₴)",
      USD: "Dollar ($)",
    },
    items: {
      title: "All items",
      searchPlaceholder: "Search...",
      category: "Category",
      allCategories: "All categories",
      allLocations: "All locations",
      sort: "Sort",
      sortDate: "By date",
      sortName: "By name",
      sortPrice: "By price",
      sortExpiry: "By expiry",
      noItems: "No items",
      addItem: "Add item",
      boughtOn: "Purchased:",
      expired: "Expired",
      daysShort: "d",
    },
    categories: {
      title: "Categories",
      namePlaceholder: "Category name",
      editTitle: "Edit category",
      name: "Name",
      addFirst: "Add your first category",
      loadStandard: "Load default categories",
      deleteTitle: "Delete category?",
      deleteDescription: "Subcategories will also be deleted. Items will remain without a category.",
      addSubcategory: "Add subcategory",
      seeded: "Categories added!",
    },
    locations: {
      title: "Locations",
      namePlaceholder: "Location name",
      editTitle: "Edit location",
      addFirst: "Add your first location",
      deleteTitle: "Delete location?",
      deleteDescription: "All sublocations will also be deleted.",
    },
    itemForm: {
      addTitle: "Add item",
      editTitle: "Edit item",
      stepBasic: "Basic",
      stepLocation: "Location",
      stepPurchase: "Purchase",
      stepNotes: "Notes",
      name: "Name *",
      namePlaceholder: "For example: MacBook Pro",
      description: "Description",
      descriptionPlaceholder: "Item description",
      barcode: "Barcode (product lookup)",
      barcodePlaceholder: "Enter barcode",
      barcodeHint: "Enter a barcode and tap search to autofill",
      photo: "Item photo",
      uploadPhoto: "Tap to upload a photo",
      maxFile: "Max 5 MB",
      useIcon: "Use icon instead of photo",
      itemIcon: "Item icon",
      category: "Category",
      selectCategory: "Choose a category",
      newCategory: "New category",
      location: "Location",
      selectLocation: "Choose a location",
      newLocation: "New location",
      purchaseDate: "Purchase date",
      price: "Price",
      currency: "Currency",
      hasExpiry: "Has expiry date",
      expiryDate: "Expiry date",
      serial: "Serial number",
      notes: "Notes",
      notesPlaceholder: "Additional information...",
      next: "Next",
      back: "Back",
      cancel: "Cancel",
      save: "Save",
      uploading: "Uploading...",
      fileTooLarge: "File is too large",
      fileTooLargeDescription: "Maximum 5 MB",
      uploadError: "Photo upload error",
      found: "Product found!",
      filled: "Data filled automatically",
      notFound: "Product not found",
      fillManual: "Try entering the data manually",
    },
    itemDetail: {
      notFound: "Item not found",
      backToList: "Back to list",
      edit: "Edit",
      deleteTitle: "Delete item?",
      deleteDescription: "This action cannot be undone.",
      location: "Location",
      purchaseDate: "Purchase date",
      price: "Price",
      expiry: "Expiry date",
      expired: "Expired",
      expiring: "Expiring",
      active: "Active",
      daysLeft: "days left",
      serial: "Serial number",
      barcode: "Barcode",
      notes: "Notes",
    },
    expiry: {
      title: "Expiry dates",
      criticalOne: "item expires in less than 7 days!",
      criticalMany: "items expire in less than 7 days!",
      expiring: "Expiring",
      active: "Active",
      expired: "Expired",
      noExpiring: "No items expiring soon",
      noActive: "No items with active expiry dates",
      noExpired: "No expired items",
      expiredShort: "expired",
      days: "days",
    },
    statistics: {
      title: "Statistics",
      totalItems: "Total items",
      totalValue: "Value",
      average: "Average",
      byCategories: "By categories",
      byLocations: "By locations",
      byMonths: "By months",
      expiry: "Expiry dates",
      active: "Active",
      expiringMonth: "Expiring this month",
      expired: "Expired",
      topFive: "Top 5 most expensive",
    },
    finance: {
      title: "Finance",
      totalSpent: "Total spending",
      purchases: "purchases",
      byDay: "Spending by day",
      byMonths: "Spending by month ({year})",
      byCategories: "Spending by category ({period})",
      recent: "Recent purchases",
    },
    notFound: {
      title: "Page not found",
      backHome: "Return home",
    },
    toasts: {
      itemAdded: "Item added",
      itemUpdated: "Item updated",
      itemDeleted: "Item deleted",
      categoryCreated: "Category created",
      categoryUpdated: "Category updated",
      categoryDeleted: "Category deleted",
      locationCreated: "Location created",
      locationUpdated: "Location updated",
      locationDeleted: "Location deleted",
      lookupError: "Lookup error",
    },
  },
};

const getTranslationValue = (language: AppLanguage, key: string): string => {
  const keys = key.split(".");
  let current: string | TranslationTree = translations[language];

  for (const part of keys) {
    if (typeof current === "string") return current;
    current = current[part];
    if (!current) {
      current = keys.reduce<string | TranslationTree | undefined>((acc, item) => {
        if (typeof acc === "string") return acc;
        return acc?.[item];
      }, translations.uk);
      break;
    }
  }

  return typeof current === "string" ? current : key;
};

const interpolate = (template: string, params?: TranslationParams) => {
  if (!params) return template;
  return template.replace(/\{(.*?)\}/g, (_, key) => String(params[key] ?? `{${key}}`));
};

const PreferencesContext = createContext<PreferencesContextType>({
  currency: "EUR",
  language: "uk",
  setCurrency: () => undefined,
  setLanguage: () => undefined,
  locale: "uk-UA",
});

export const PreferencesProvider = ({ children }: { children: ReactNode }) => {
  const [currency, setCurrencyState] = useState<AppCurrency>("EUR");
  const [language, setLanguageState] = useState<AppLanguage>("uk");

  useEffect(() => {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    if (!raw) return;

    try {
      const parsed = JSON.parse(raw) as Partial<{ currency: AppCurrency; language: AppLanguage }>;
      if (parsed.currency === "EUR" || parsed.currency === "UAH" || parsed.currency === "USD") {
        setCurrencyState(parsed.currency);
      }
      if (parsed.language === "uk" || parsed.language === "ru" || parsed.language === "en") {
        setLanguageState(parsed.language);
      }
    } catch {
      window.localStorage.removeItem(STORAGE_KEY);
    }
  }, []);

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify({ currency, language }));
    document.documentElement.lang = language;
  }, [currency, language]);

  const value = useMemo(
    () => ({
      currency,
      language,
      setCurrency: setCurrencyState,
      setLanguage: setLanguageState,
      locale: getLocaleFromLanguage(language),
    }),
    [currency, language],
  );

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
};

export const usePreferences = () => useContext(PreferencesContext);

export const useI18n = () => {
  const preferences = usePreferences();

  const t = (key: string, params?: TranslationParams) => {
    return interpolate(getTranslationValue(preferences.language, key), params);
  };

  return { ...preferences, t };
};

export const formatNumberByLocale = (value: number, locale: string) => value.toLocaleString(locale);

export const formatDateByLocale = (
  value: string | number | Date,
  locale: string,
  options?: Intl.DateTimeFormatOptions,
) => new Date(value).toLocaleDateString(locale, options);

export const formatMonthYearByLocale = (value: string | number | Date, locale: string) =>
  new Intl.DateTimeFormat(locale, { month: "long", year: "numeric" }).format(new Date(value));

export const formatMonthShortByLocale = (value: string | number | Date, locale: string) =>
  new Intl.DateTimeFormat(locale, { month: "short" }).format(new Date(value));

export const getDateFnsLocale = async (_language: AppLanguage) => null;
